services:
  - name: "ShenJun's Blog"
    api:
      - url: "https://blog.shenjun.cc"
  - name: "My Services"
    api:
      - url: "https://github.com/conanyangqun"
      - url: "https://health.shenjun.cc"
